"""empty message

Revision ID: 0959ad3a62fd
Revises: 7c1247b2cf71
Create Date: 2022-04-02 10:45:24.767284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0959ad3a62fd'
down_revision = '7c1247b2cf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
