"""empty message

Revision ID: 209d473e2b3d
Revises: 5bcb0f52bd0d
Create Date: 2022-04-02 11:07:18.728939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209d473e2b3d'
down_revision = '5bcb0f52bd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('sex', sa.VARCHAR(length=1), nullable=False))
    # ### end Alembic commands ###
