"""empty message

Revision ID: 4405f84fdcfe
Revises: 2378f43aafc9
Create Date: 2022-04-02 10:39:02.992238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4405f84fdcfe'
down_revision = '2378f43aafc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
