"""empty message

Revision ID: 54c53d60cd8e
Revises: 209d473e2b3d
Create Date: 2022-04-02 11:07:41.811574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c53d60cd8e'
down_revision = '209d473e2b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('sex', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'sex')
    # ### end Alembic commands ###
